### ISSUE TITLE
Use `dplyr::ntile()` instead of custom `quantise()` function

### ISSUE THREAD

**Issue by matthewgthomas** [humaniverse/compositr#5]
`dplyr::ntile()` does everything we need for create quantiles - let's use that instead and remove our `quantise()` function.

**Comment by MikeJohnPage** [comment]
I like the `quantise()` funciton currently in compositr because it:

- Allows easy inversion of qunatiles via the `invert` argument
- Throws a warning if the quantiles are not in equal bins. I think this is important because it might prevent silent mistakes creeping into analyses.
- We can expand it to add new quantising methods in the future.

For now, I am going to mark the function with `@keyword internal` to prevent it being exported by the package.

**Comment by MikeJohnPage** [comment]
I just found a nasty bug in the original `calculate_extent()` which uses `dplyr::ntile()` to calculate percentiles like so:

```r
data <- data |>
    dplyr::mutate(percentile = dplyr::ntile(x, 100))
```
Here, the function is not creating percentiles like we initially thought. For example look at the following output:

```r
> dplyr::ntile(201:210, 100)
 [1]  1  2  3  4  5  6  7  8  9 10
```
This means extent scores are not calculated properly further in the function, where it expects the percentile scores to be in a range from 1-100. Here, the `quantise()` funciton as part of this package gives the expected answer:

```r
> quantise(201:210, 100)
 [1]   1  12  23  34  45  56  67  78  89 100
```

**Comment by MikeJohnPage** [comment]
@matthewgthomas due to the above reasons, I'm keeping `quantise()` in the package and closing the issue. Feel free to repon it if you disagree!
